### ISSUE TITLE
URI Builder & URI Parser

### ISSUE THREAD

**Issue by Nickadiemus** [karthiknayak02/insidecirclesports#7]
Implementation of Utility functions for API calls (if needed). This will allow to efficiently build any url with query strings and also parse any url response. 

Primary Use will be for open authentication (oAUTH) for users to sign up with external profiles (Facebook, Twitter, Google, etc.)

function buildURL()

function parseQueryString()

**Comment by Nickadiemus** [comment]
Utility functions finished

**Comment by sapjoldaccount** [comment]
@Nickadiemus what branch are you doing this in?

**Comment by Nickadiemus** [comment]
the **Skeleton** Branch @stevenpenavajr
